//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.20 at 09:30:39 PM EET 
//


package demo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for messageInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="messageInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fromPhone" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="toPhone" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="fontColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fontFamily" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fontSize" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="isUnderline" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isBold" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isItalic" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="backgroundColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "messageInfo", propOrder = {
    "fromPhone",
    "toPhone",
    "content",
    "date",
    "fontColor",
    "fontFamily",
    "fontSize",
    "isUnderline",
    "isBold",
    "isItalic",
    "backgroundColor"
})
public class MessageInfo {

    protected byte fromPhone;
    protected byte toPhone;
    @XmlElement(required = true)
    protected String content;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlElement(required = true)
    protected String fontColor;
    @XmlElement(required = true)
    protected String fontFamily;
    protected byte fontSize;
    @XmlElement(required = true)
    protected String isUnderline;
    @XmlElement(required = true)
    protected String isBold;
    @XmlElement(required = true)
    protected String isItalic;
    @XmlElement(required = true)
    protected String backgroundColor;

    /**
     * Gets the value of the fromPhone property.
     * 
     */
    public byte getFromPhone() {
        return fromPhone;
    }

    /**
     * Sets the value of the fromPhone property.
     * 
     */
    public void setFromPhone(byte value) {
        this.fromPhone = value;
    }

    /**
     * Gets the value of the toPhone property.
     * 
     */
    public byte getToPhone() {
        return toPhone;
    }

    /**
     * Sets the value of the toPhone property.
     * 
     */
    public void setToPhone(byte value) {
        this.toPhone = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the fontColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFontColor() {
        return fontColor;
    }

    /**
     * Sets the value of the fontColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFontColor(String value) {
        this.fontColor = value;
    }

    /**
     * Gets the value of the fontFamily property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFontFamily() {
        return fontFamily;
    }

    /**
     * Sets the value of the fontFamily property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFontFamily(String value) {
        this.fontFamily = value;
    }

    /**
     * Gets the value of the fontSize property.
     * 
     */
    public byte getFontSize() {
        return fontSize;
    }

    /**
     * Sets the value of the fontSize property.
     * 
     */
    public void setFontSize(byte value) {
        this.fontSize = value;
    }

    /**
     * Gets the value of the isUnderline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsUnderline() {
        return isUnderline;
    }

    /**
     * Sets the value of the isUnderline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsUnderline(String value) {
        this.isUnderline = value;
    }

    /**
     * Gets the value of the isBold property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsBold() {
        return isBold;
    }

    /**
     * Sets the value of the isBold property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsBold(String value) {
        this.isBold = value;
    }

    /**
     * Gets the value of the isItalic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsItalic() {
        return isItalic;
    }

    /**
     * Sets the value of the isItalic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsItalic(String value) {
        this.isItalic = value;
    }

    /**
     * Gets the value of the backgroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundColor() {
        return backgroundColor;
    }

    /**
     * Sets the value of the backgroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundColor(String value) {
        this.backgroundColor = value;
    }

}
